// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/ng-cordova/emailComposer.d.ts
declare namespace ngCordova {

  export interface IEmailComposerOptions {
        to: string | Array<string>;
        cc?: string | Array<string>;
        bcc?: string | Array<string>;
        attachments?: Array<any>;
        subject?: string;
        body?: string;
        isHtml?: boolean;
    }

  export interface IEmailComposerService {

    isAvailable(): ng.IPromise<boolean>;
    open(properties: IEmailComposerOptions) : ng.IPromise<any>;
    addAlias(app: string, schema: string) : void;

  }

}
